# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Découverto Podcasts
email: decouverto@yahoo.fr
description: "Les podcasts Découverto: site regroupant l'ensemble des podcasts Découverto comprennant notamment Mémoire de Territoire."
subtitle: "Un instant de découverto avec Découverto."
lang: fr-fr
author: Découverto
copyright: "CC-BY 4.0"
baseurl: "/podcast" # the subpath of your site, e.g. /blog
url: "https://decouverto.github.io" # the base hostname & protocol for your site
github_username:  decouverto

permalink: /:year/:title.html

#Timezone
timezone: France/Paris

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

theme: jekyll-theme-minimal
